### ISSUE TITLE
No CSS Files

### ISSUE THREAD

**Issue by ghost** [eternalxlks/eternal-strap#1]
There appear to be no CSS files in the project's root directory. Clicking the only file besides the README file shows a Bootstrap template. If you want a simple CSS template for your library, here's one:

```css
/*
A Bootstrap-like body template to get you started.
*/
body {
    font-family: Arial, sans-serif;
    padding: 0px;
    margin: 0px;
}

/*
Several color templates too.
*/
.red {
    color: #ff0000;
}

.yellow {
    color: #00ff00;
}

.green {
    color: #0000ff;
}

.white {
    color: #ffffff;
}

.black {
    color: #000000;
}
```
